### ISSUE TITLE
dbpool failed to detach

### ISSUE THREAD

**Issue by beckhamrryyaann** [IBM/nodejs-idb-pconnector#106]
**Please complete the following information:**
- Node.js version: 12.18.4
- idb-connector version: 1.2.9
- idb-pconnector version: 1.0.8
- IBM i version: v7r2 (2 7)

**Describe the bug**

I have an application and trying to use DBPool to handle any connections.  I have created one pool that is used through out the life of the web application.  The pool is created when web app is started.  Every so often I will get fail to detach error.  It doesn't happen everytime.  From my understanding when using DBPool i do not need to worry about closing connections.  That is handled by the runSql and prepareExecute.  Is this not the recommended use for a DBPool?

Database.js
```
const {DBPool} = require('idb-pconnector');
const pool = new DBPool();
module.exports = pool;

```

DepartmentJobs.js
```
'use strict'
const pool = require('./Database');

class DepartmentJobs {
    constructor(...) {
      ...
    }

    static async get() {
        let stmt = "SELECT . . . . . From . . . . ";

        try {
            const results = await pool.runSql(stmt);
            return results;
        } catch(error) {

        }
    }
}

module.exports = DepartmentJobs;
```
error when running command.
```
Error: DBPool: Failed to detach()
    at DBPool.detach (/webservices/workassist/node_modules/idb-pconnector/lib/dbPool.js:114:22)
Caused By:
 Error: DBPoolConnection: failed to detach.
    at DBPoolConnection.detach (/webservices/workassist/node_modules/idb-pconnector/lib/dbPoolConnection.js:127:22)
Caused By:
 Error: Statement failed to close, new Statement could not be created.
    at DBPoolConnection.newStatement (/webservices/workassist/node_modules/idb-pconnector/lib/dbPoolConnection.js:75:24)
Caused By:
 Error: SQLSTATE=PAERR SQLCODE=-1 SQLFreeStmt failed.
    at /webservices/workassist/node_modules/idb-pconnector/lib/statement.js:77:22
    at new Promise (<anonymous>)
    at Statement.close (/webservices/workassist/node_modules/idb-pconnector/lib/statement.js:75:12)
    at DBPoolConnection.newStatement (/webservices/workassist/node_modules/idb-pconnector/lib/dbPoolConnection.js:73:30)
    at DBPoolConnection.detach (/webservices/workassist/node_modules/idb-pconnector/lib/dbPoolConnection.js:123:20)
    at DBPool.detach (/webservices/workassist/node_modules/idb-pconnector/lib/dbPool.js:112:24)
    at /webservices/workassist/node_modules/idb-pconnector/lib/dbPool.js:210:20
    at async DBPool.runSql
```

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
I should be able to setup the (global) DBPool and have all connections use this pool.  I would assume if a connection is not available then more would be created so there will be no errors.  I would not expect a failed to detach error.  Is this something i can safely `ignore?`

**Screenshots**

**Additional context**

**Comment by abmusse** [comment]
> From my understanding when using DBPool i do not need to worry about closing connections. That is handled by the runSql and prepareExecute. Is this not the recommended use for a DBPool?

Right using `runSql` and `prepareExecute` aggregates (runSql and prepareExecute) are there to simplify your code. Getting a connection from the pool, then getting a statement and executing the statement, and finally closing the statement and returning the connection to the pool. I would say your use case suites using DBPool.


The bug you encountered looks to occur when the DbPoolConnection detaches and therefore attempts to cleanup the current statement and create a new one. https://github.com/IBM/nodejs-idb-pconnector/blob/master/lib/dbPoolConnection.js#L123. On the `idb-connector` side there is a failure when calling [statement.close()](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L1821) and a [custom error message](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dberror.h#L93): `SQLSTATE=PAERR SQLCODE=1` is printed. Can you enable debug on the pool so we can see the actually [sql return code printed from idb-connector](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L1820) ?

```js
  const pool = new DBPool({}, {debug: true});
```

Also have you ran into this same issue when using `prepareExecute` or only with `runSql` Failing to close the statement handle is a bit concerning and would definitely would like to know why it failed.

**Comment by beckhamrryyaann** [comment]
Yes...my co worker has also written another nodejs app using the same
structure as mine and she is encountering the same problem using the
prepareExecute function.  At first we figured we had some sort of code
issue on our end but once i received the error again using runSql I thought
I better ask the experts.

I will set debug:true  on the DBPool and report back when it happens
again.  Thanks for your help.

As a side note: the way I am creating the DBPool, it will be alive for the
life of the server.  Is this how you intended this to work?  I don't see
any value in creating/closing a new DBPool each time a user makes a
request??  I do not want to waste your time if I am not using DBPool
correctly.

**Comment by abmusse** [comment]
Yes I think having one pool is correct.

**Comment by beckhamrryyaann** [comment]
Something to throw out there...it does appear to only happen after the pool has set idle for a longer period of time.  I left my web server running over night...came in this morning and got the error first time I tried to run...after that it has worked fine....not sure that means anything just yet...just an observation....is there a timeout to the connections?

**Comment by abmusse** [comment]
Interesting, it could be that the statement handle becomes invalid over time and therefore unable to to free an invalid handle. One of the possible return codes for [SQLFressStmt](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/cli/rzadpfnfstmt.htm) is `SQL_IN_HANDLE`. Would be interesting to see if that is returned and logged when the error is reproduced in debug mode.

**Comment by beckhamrryyaann** [comment]
```
Finding available Connection...
Connection 0 found
Preparing Statement...
Prepare().
SQLPrepare(0): CALL mmiprod01.fab_po_ack(?,?,?)
Binding Parameters...
Size of BoundParams: 3 
 [["204741",1,1],["",1,1],["",3,1]]
BindParamAsync().
SQLBindParameter(0) TYPE[ 1] SIZE[  8] DIGI[0] IO[1] IND[ -3] INDEX[0]
SQLBindParameter(0) TYPE[ 1] SIZE[  5] DIGI[0] IO[1] IND[ -3] INDEX[1]
SQLBindParameter(0) TYPE[ 1] SIZE[250] DIGI[0] IO[3] IND[ -3] INDEX[2]
Execute().
SQLExecuteAsync(1):
SQLNUMRESULTSCOLS(0) Column Count = 0
NO RESULTS :SQLExecuteAsync()
Fetching Result Set...
FetchAllAsync().

 **** ERROR *****
SQLSTATE: HY010
Native Error Code: -99999
Error occurred in SQL Call Level Interface 
SQL did not return a result set.
SQLFreeStmt: stmth 3 [SQL_DROP]
SQLFreeStmt(0)
success: true                                                                                                                                                                                                                                             
[0mPATCH /api/fabric/po/204741?action=ack [32m200 [0m14.362 ms - 16[0m
Finding available Connection...
Connection 0 found
Preparing Statement...
Prepare().
SQLPrepare(-1): SELECT * FROM QS36F.FABORD WHERE FOOTYP = ? AND FOPO# = ?

 **** ERROR *****
SQLSTATE: HY017
Native Error Code: -99999
Error occurred in SQL Call Level Interface 
Detaching Connection 0...
SQLFreeStmt: stmth 3 [SQL_DROP]
SQLFreeStmt(-1)
[0mPATCH /api/fabric/po/204741?action=ack [32m200 [0m4.664 ms - 56[0m
```

looks like HY017 maps to "connection no longer available"...seems like the timeout is the issue at first glance.

**Comment by abmusse** [comment]
From the log looks like `SQLExecute` returned success with info i.e. `(1)`. [SQLExecuteAsync(1)](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L1004). Then FetchAll is called and it appears this is where the:

```
 **** ERROR *****
SQLSTATE: HY010
Native Error Code: -99999
Error occurred in SQL Call Level Interface 

```

Is printed before the statment is freeed.

The next time connection 0 is returned from the pool the `SQLPrepare(-1)` failed. Looking at the docs for [SQLPrepare](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/cli/rzadpfnprep.htm) I did not see `HY017` listed there. @beckhamrryyaann Where did you see `HY017` maps to "connection no longer available"?

@kadler @ThePrez @forstie

Do you know if connection/statements created with SQLCLI have a timeout value?

**Comment by beckhamrryyaann** [comment]
I found this link that gave me a clue to what it meant.
[https://www.ibm.com/support/pages/apar/PK42850]
We can replicate this issue on demand at the moment.  As said, we let the pool sit idle over night...we come in this morning and attempted to make a request, and we get this error....If we restart the server, it will work normally until it sits awhile.

**Comment by abmusse** [comment]
That issue does seem to resemble what your experiencing. Seems like we need to add way to check if a connection/statement is still available before we attempt to use it.

**Comment by abmusse** [comment]
@beckhamrryyaann 

I suspect the QSQSRVR ends which causes the connections to invalidate. Any messages in your in the job log related to QSQSRVR ending?

As a workaround we may need to add a call to ensure the connection is still active and stale before doing any of the runsql / prepareExecute work.

**Comment by beckhamrryyaann** [comment]
I'm not exactly sure where to look for a closed qsqsrvr job? I haven't
noticed any.

It seems like this is a very possible scenario for many users, where a pool
might sit idle over night, or even days??
It seems making sure the connections in the pool are still valid would be a
must??

I hope to put this app in production by the end of month, and really hope I
can use the enhancements that DBPool brings.

**Comment by abmusse** [comment]
Yes the connections are expected to stay open. I'm not sure why your connections become inactive overnight. I've tested an web app running for multiple days and the connections are still active.

I created a branch that adds an API to get the fully qualified job name for the connection. This calls [SQLGetInfo](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/cli/rzadpfnginfo.htm) with `SQL_CONNECTION_JOB_NAME` option:

![image](https://user-images.githubusercontent.com/33973272/100653594-45e31200-330e-11eb-964a-185472e5ad9e.png)


It will log the job name whenever `runSql` or `prepareExecute` is called and debug is enabled. You can try using this to get connection job name and go from there checking for job logs / spool files.


You can test this version with:

```
npm install --save abmusse/nodejs-idb-pconnector#add-getJobName
```

**Comment by beckhamrryyaann** [comment]
thank you. I will try this.

**Comment by ThePrez** [comment]
Go away, stale-bot!

**Comment by abmusse** [comment]
> Go away, stale-bot!

We can apply the `keep-open` label and stale bot will not close the issue/ PR

**Comment by beckhamrryyaann** [comment]
Thanks for your help.  I do believe I found the problem and hope I didn't
waste  too much of your time.  Apparently one of my coworkers had written a
CL program that killed a lot of the QSQSRVR jobs.....so the idb connector
was working correctly.  The job had been killed out from under it. It might
be beneficial to make sure the connection is still active before using??
(if possible) or somehow check the integrity of the pool....or just leave
your code as is since it works....

again thanks for your help.

Ryan

**Comment by abmusse** [comment]
Glad you were able find out why the connection was being killed.

AFAIK there isn't a straight forward way to check if the connection is still active with SQLCLI other than calling method and checking the return code. One way could be attempting to call  [SQLGetInfo](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/cli/rzadpfnginfo.htm) with `SQL_CONNECTION_JOB_NAME` option. When the connection handle is active, you will get the job name. When it is not, you will get back SQLSTATE 08003 Connection not open.
